#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Checking for changes to tests or package.json..."
echo "Do not make any changes to tests or package.json."

git diff --quiet src/**/test.js
git diff --quiet package.json
