name: create-branch

on: fork

jobs:
  build:
    name: Create Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const creator = context.actor
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/${creator}`,
              sha: process.env.GITHUB_SHA
            })
